apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: manager-app-prod
  title: Manager App (Prod)
  description: Management module for the Mind BSS production environment.
  tags:
    - management
    - production
  links:
    - url: https://frontend1-v8.mind.belizetelemedia.net:8443/MindBill-Manager
      title: Open Manager App (Prod)
      icon: dashboard
spec:
  type: website
  lifecycle: production
  system: mind-bss
  owner: btl-product-solutions
  subcomponentOf: mind-bss-prod

