apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mindbill-admin-staging
  title: MINDBILL Administration & Management (staging)
  description: Administration and management modules for the Mind BSS staging environment.
  tags:
    - mindbill
    - admin
    - staging
  links:
    - url: https://stagingfrontend.mind.belizetelemedia.net:8443/MINDBill/
      title: Open MINDBILL Admin & Management (staging)
      icon: dashboard
spec:
  type: website
  lifecycle: staging
  owner: btl-product-solutions
  subcomponentOf: mind-bss-staging

