apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: csr-portal-staging
  title: MINDBILL CSR (staging)
  description: CSR portal for staging BSS.
  tags:
    - csr
    - staging
  links:
    - url: https://stagingfrontend.mind.belizetelemedia.net:8443/WebClient/
      title: CSR Portal (staging)
      icon: dashboard
spec:
  type: website
  lifecycle: staging
  owner: btl-product-solutions
  subcomponentOf: mind-bss-staging

